# Generated by Django 2.1.7 on 2019-02-15 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190215_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Actor',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.Actor'),
        ),
    ]
