# Generated by Django 2.1.7 on 2019-02-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190215_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='actor',
            name='last_name',
            field=models.CharField(default='p', max_length=50),
            preserve_default=False,
        ),
    ]
