# Generated by Django 2.1.7 on 2019-02-15 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190215_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movie_cast_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.Movie'),
        ),
    ]
