# Generated by Django 2.1.5 on 2019-02-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190215_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movie_cast_in',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.Actor'),
        ),
    ]
